/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
    implementation(project(":domain"))

    implementation 'org.hibernate.orm:hibernate-core:6.5.0.Final'
    implementation 'jakarta.persistence:jakarta.persistence-api:3.0.0'
    implementation 'mysql:mysql-connector-java:8.3.0'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.9.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.9.0'
}