/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.bookstore.backoffice;

import cat.teknos.bookstore.domain.jdbc.models.JdbcModelFactory;
import cat.teknos.bookstore.domain.jpa.models.JpaModelFactory;
import com.albertdiaz.bookstore.models.ModelFactory;
import com.albertdiaz.bookstore.repositories.RepositoryFactory;


import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.util.Properties;

public class App {
    public static void main(String[] args) throws ClassNotFoundException, NoSuchMethodException, InvocationTargetException, InstantiationException, IllegalAccessException, IOException {
        var properties = new Properties();
        properties.load(App.class.getClassLoader().getResourceAsStream("app.properties"));

        RepositoryFactory repositoryFactory = (RepositoryFactory) Class.forName(properties.getProperty("repositoryFactory")).getConstructor().newInstance();
        ModelFactory modelFactory = new JpaModelFactory();

        var backoffice = new BackOffice(System.in, System.out, repositoryFactory, modelFactory);
        backoffice.start();
    }
}
